name: hsg
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults

dependencies:
  - python<=3.10.8
  - numpy<2.0
  - hickle
  - lightning
  # - pytorch-cuda=11.8
  - xarray==0.19.0
  - pip
  - pip:
      - decord
      - fvcore
      - lpips
      - pandas
      - scikit-image<=0.19.3
      - timm<=0.6.11
      - tqdm
      - einops
      - transformers>=4.18.0

# prefix: D:/Software/Miniconda/envs/hsg
