"""Development protocol and fail-closed prerequisites for Issue #107.

Allocation is not an audit freeze: no audit data may be generated by this
development implementation. A later freeze must bind successful development
evidence, code, data, thresholds and the complete seed factorial.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path

PROTOCOL = "relational_emergence.phase1.v2.dev1"
V1_COMMIT = "148b25663a40f8f4b2385956166859efebec8a81"
MECHANISMS = ("free", "unilateral_contact", "bilateral_coupling", "confining_boundary")
LEGACY = dict(
    zip(MECHANISMS, ("free", "support", "attachment", "containment"), strict=True)
)
FROM_LEGACY = {value: key for key, value in LEGACY.items()}
DEV_FAMILIES = tuple(f"v2_dev_{i}" for i in range(4))
AUDIT_FAMILIES = tuple(f"v2_audit_{i}" for i in range(4))
DEV_SEED = 2026092302
AUDIT_SEED = 2027021702


@dataclass(frozen=True)
class Protocol:
    version: str = PROTOCOL
    objects: int = 4
    groups_per_tuple: int = 24
    cutoff: int = 10
    horizon: int = 20
    prediction_steps: int = 10
    seeds: tuple[int, ...] = (11, 23, 37, 53, 71)
    leakage_mde_ce: float = 0.05
    alpha: float = 0.05
    power: float = 0.8
    numerical_tolerance: float = 1e-8

    def __post_init__(self) -> None:
        if self.version != PROTOCOL:
            raise ValueError("unsupported protocol version")
        if self.objects not in (3, 4):
            raise ValueError("v2 requires 3 or 4 objects")
        if self.cutoff < 1 or self.prediction_steps < 1:
            raise ValueError("history and prediction windows must be positive")
        if self.cutoff + self.prediction_steps > self.horizon:
            raise ValueError("future targets must exist; padding is forbidden")
        if self.groups_per_tuple < 4 or len(set(self.seeds)) < 3:
            raise ValueError("need grouped splits and at least three independent seeds")
        if len(self.seeds) != len(set(self.seeds)):
            raise ValueError("training seeds must be unique")
        if not 0 < self.alpha < 1 or not 0 < self.power < 1 or self.leakage_mde_ce <= 0:
            raise ValueError("invalid audit thresholds")

    def digest(self) -> str:
        from ..simulator.state import DEFAULT_CONSTANTS

        return digest(
            {
                "protocol": asdict(self),
                "physics": asdict(DEFAULT_CONSTANTS),
                "development_seed": DEV_SEED,
                "audit_seed": AUDIT_SEED,
                "development_families": DEV_FAMILIES,
                "audit_families": AUDIT_FAMILIES,
                "mechanisms": LEGACY,
            }
        )


def digest(value: object) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, allow_nan=False).encode()
    ).hexdigest()


def code_digest() -> str:
    root = Path(__file__).resolve().parents[1]
    return digest(
        {
            path.relative_to(root).as_posix(): hashlib.sha256(
                path.read_bytes()
            ).hexdigest()
            for path in sorted(root.rglob("*.py"))
        }
    )


def require_phase_ib(evidence: dict, protocol: Protocol, dataset_digest: str) -> None:
    """Never let a v1 result, stale file, missing gate or smoke run authorize IB."""
    expected = {
        "protocol_sha256": protocol.digest(),
        "code_sha256": code_digest(),
        "dataset_sha256": dataset_digest,
        "verdict": "GO_PHASE_IA_V2",
        "m0": "PASS_NO_DETECTABLE_LEAKAGE",
        "evaluator_controls": "PASS",
        "transplant_controls": "PASS",
        "level2": "PASS",
        "multi_object": "PASS",
        "chronology_control": "PASS",
    }
    failures = [key for key, value in expected.items() if evidence.get(key) != value]
    selected = evidence.get("selected_horizon")
    if not isinstance(selected, int) or not 1 <= selected <= min(
        protocol.cutoff, protocol.prediction_steps
    ):
        failures.append("selected_horizon")
    if evidence.get("training_seeds") != list(protocol.seeds):
        failures.append("training_seeds")
    if failures:
        raise ValueError("Phase IB v2 blocked: " + ", ".join(failures))
